"""Add user-analysis relationship

Revision ID: b5be7094467b
Revises: 43b9164ad2f3
Create Date: 2024-10-23 19:31:42.187893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5be7094467b'
down_revision = '43b9164ad2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
