"""Initial migration

Revision ID: d34539edc087
Revises: b5be7094467b
Create Date: 2024-10-23 22:42:29.296160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34539edc087'
down_revision = 'b5be7094467b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
